@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\UltimateScpiCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=USBVoltage
SET Values=0.000000
SET LowLimit=0.0
SET UpLimit=5.0
SET TargetLimit=5.0
SET VarResultSummary=
SET LogFile=C:\Users\TE\Desktop\Meridian_audioandbtble_PB3\BLE_NOR_MT\UltimateScpiCmd.log
SET InputFile=
