@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\UltimateScpiCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=BLEFREQOffset
SET Values=-3230.000000
SET LowLimit=-75000
SET UpLimit=75000
SET TargetLimit=25000
SET VarResultSummary=
SET LogFile=D:\Bolide_BLE-PB2\UltimateScpiCmd.log
SET InputFile=
