@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\UltimateControlCmd.exe
SET Status=1
SET ReturnCode=1
SET Message=[E]:"Failure string value not the same."
SET Headers=Audioversion
SET Values=8.0.73
SET LowLimit=8.0.63
SET UpLimit=8.0.63
SET TargetLimit=8.0.63
SET VarResultSummary=8.0.73
SET LogFile=test.log
SET InputFile=
