lvreg eeprom read c0
lvreg eeprom read c1
lvreg eeprom read c2
lvreg eeprom read c3
lvreg eeprom read c4
lvreg eeprom read c5
lvreg eeprom read c6
lvreg eeprom read c7
lvreg eeprom read c8
lvreg eeprom read c9
lvreg eeprom read ca
lvreg eeprom read cb
lvreg eeprom read cc
lvreg eeprom read cd
lvreg eeprom read ce
lvreg eeprom read cf
lvreg eeprom read d0
lvreg eeprom read d1
lvreg eeprom read d2
lvreg eeprom read d3
lvreg eeprom read d4
lvreg eeprom read d5
lvreg eeprom read d6
lvreg eeprom read d7
lvreg eeprom read d8
lvreg eeprom read d9
lvreg eeprom read da
lvreg eeprom read db
lvreg eeprom read dc
lvreg eeprom read dd
lvreg eeprom read de
lvreg eeprom read df
lvreg eeprom read e0
lvreg eeprom read e1
lvreg eeprom read e2
lvreg eeprom read e3
lvreg eeprom read e4
lvreg eeprom read e5
lvreg eeprom read e6
lvreg eeprom read e7
lvreg eeprom read e8
lvreg eeprom read e9
lvreg eeprom read ea
lvreg eeprom read eb
lvreg eeprom read ec
lvreg eeprom read ed
lvreg eeprom read ee
lvreg eeprom read ef
lvreg eeprom read f0
lvreg eeprom read f1
pause