@Echo off
REM Please do not modify this file, this file is generated by C:\Program Files (x86)\Common Files\Logitech\EasyAVRuntimeEngine\EasyLensMotorCmd.exe
SET Status=1
SET ReturnCode=1
SET Message=[E]:"N3(1), Failure up limit! (Up=11) >= (Value=12.000000) >= (Low=-1)"
SET Headers=N1(1),N1(2),N1(3),N3(1),N3(2),N3(3),Variation, VarResultSummary
SET Values=10.000000 ,10.000000 ,10.000000 ,12.000000 ,12.000000 ,12.000000 , 2.000000, 10.000000
SET LowLimit=-1,-1,-1,-1,-1,-1,-1,-1
SET UpLimit=11,11,11,11,11,11,5,11
SET TargetLimit=0,0,0,0,0,0,0,0
SET VarResultSummary=0X0A
SET LogFile=Bolide_Focus.log
SET InputFile=
