@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\UltimateScpiCmd.exe
SET Status=1
SET ReturnCode=1
SET Message=[E]:"Failure string value not the same."
SET Headers=Extension code,Result code,Average power,Max avg power,Min avg power,Peak to avg power,Number fail,Number tested,Result
SET Values=LEOP0,FALSE,0.00,0.00,0.00,0.00,0,0,FAIL
SET LowLimit=LEOP0,TRUE,-100.0,-100.0,-100.0,-100.0,-100.0,-100.0,PASS
SET UpLimit=LEOP0,TRUE,100.0,100.0,100.0,100.0,100.0,100.0,PASS
SET TargetLimit=LEOP0,TRUE,100.0,100.0,100.0,100.0,100.0,100.0,PASS
SET VarResultSummary=
SET LogFile=C:\Users\TE\Desktop\Meridian_audiobt_PB3\bletest\UltimateScpiCmd.log
SET InputFile=
