@Echo off
REM Please do not modify this file, this file is generated by c:\Program Files (x86)\Common Files\Logitech\EasyAVRuntimeEngine\EasyLensMotorCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=N1(1),N1(2),N1(3),N3(1),N3(2),N3(3),Variation,VarResultSummary
SET Values=1.000000 ,1.000000 ,2.000000 ,1.000000 ,2.000000 ,2.000000 , 1.000000, 1.000000
SET LowLimit=0,0,0,0,0,0,0,0
SET UpLimit=3,3,3,3,3,3,2,3
SET TargetLimit=0,0,0,0,0,0,0,0
SET VarResultSummary=0X01
SET LogFile=Bolide_Zoom.log
SET InputFile=
