REM Please do not modify this file, this file is generated by c:\Program Files\Common Files\Logitech\EasyAVRuntimeEngine\EasyLensMotorCmd.exe
SET Status=0
SET ReturnCode=0
SET Message=Ok!
SET Headers=Backlash(1),Backlash(2),Backlash(3),variation, VarResultSummary
SET Values=1.000000 ,1.000000 ,1.000000 , 0.000000, 1.000000
SET LowLimit=-1,-1,-1,0,-1
SET UpLimit=8,4,4,3,4
SET TargetLimit=0,0,0,0,0
SET LogFile=test.log
SET VarResultSummary=0X01
